/**
 * Embed the companion web client's strings.
 *
 * The phone page is a single embedded HTML file served by the Rust
 * companion server. Its UI strings are the SAME `companion.*` keys the app
 * locales ship (one source of truth), so this script extracts that object
 * from every locale's translation.json into a committed Rust source file
 * (strings_gen.rs) the server inlines into the page at serve time.
 *
 * Hard-fails when any locale is missing any key, so locale completeness is
 * enforced here as well as by `bun run check:translations`.
 *
 * Regenerate after editing companion strings:
 *   bun scripts/embed-companion-strings.ts
 */
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const LOCALES_DIR = path.join(__dirname, "..", "src", "i18n", "locales");
const OUT_PATH = path.join(
  __dirname,
  "..",
  "src-tauri",
  "src",
  "companion",
  "strings_gen.rs",
);

type Strings = Record<string, string>;

function loadCompanionStrings(lang: string): Strings {
  const file = path.join(LOCALES_DIR, lang, "translation.json");
  const data = JSON.parse(fs.readFileSync(file, "utf8"));
  const companion = data.companion;
  if (typeof companion !== "object" || companion === null) {
    throw new Error(`locale '${lang}' has no companion.* strings`);
  }
  return companion as Strings;
}

function main(): void {
  const langs = fs
    .readdirSync(LOCALES_DIR, { withFileTypes: true })
    .filter((e) => e.isDirectory())
    .map((e) => e.name)
    .sort();

  if (!langs.includes("en")) {
    throw new Error("reference locale 'en' is missing");
  }

  const reference = loadCompanionStrings("en");
  const referenceKeys = Object.keys(reference).sort();

  const all: Record<string, Strings> = {};
  for (const lang of langs) {
    const strings = loadCompanionStrings(lang);
    const missing = referenceKeys.filter((key) => !(key in strings));
    if (missing.length > 0) {
      throw new Error(
        `locale '${lang}' is missing companion keys: ${missing.join(", ")}`,
      );
    }
    // Keep exactly the reference keys, in reference order, so the embedded
    // blob stays stable across meaningless locale-dir ordering.
    const ordered: Strings = {};
    for (const key of referenceKeys) {
      const value = strings[key];
      if (typeof value !== "string" || value.length === 0) {
        throw new Error(
          `locale '${lang}' key '${key}' is empty or not a string`,
        );
      }
      ordered[key] = value;
    }
    all[lang] = ordered;
  }

  const header = `// GENERATED by scripts/embed-companion-strings.ts - DO NOT EDIT.
// The companion web client's strings for every app locale, as one JSON
// blob inlined into the served page. Missing keys fail the generator, so
// this file can never lag the locales.

`;

  // A raw string literal is safe: translations never contain the sequence
  // `"#` (checked below, belt and braces).
  const json = JSON.stringify(all);
  if (json.includes('"#')) {
    throw new Error("translation values contain the raw-string terminator");
  }

  const rust = `${header}pub const ALL: &str = r#"${json}"#;
`;
  fs.writeFileSync(OUT_PATH, rust);
  console.log(
    `embedded companion strings for ${langs.length} locales (${referenceKeys.length} keys) -> ${path.relative(process.cwd(), OUT_PATH)}`,
  );
}

main();
