
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async changeBinding(id: string, binding: string) : Promise<Result<BindingResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_binding", { id, binding }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resetBinding(id: string) : Promise<Result<BindingResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reset_binding", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeShortcutActivationSetting(activation: ShortcutActivation) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_shortcut_activation_setting", { activation }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeHoldThresholdMsSetting(ms: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_hold_threshold_ms_setting", { ms }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAudioFeedbackSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_audio_feedback_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeMemoryPressureGuardSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_memory_pressure_guard_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Persist the memory-gate safety margin (Advanced settings). Mirrors the
 * store-side load guard: margins of 1-4 MB are invalid (neither off nor a
 * usable margin) and normalize to 0, so a value written here can never be
 * silently rewritten on the next load. The UI already rejects 1-4; this is
 * the same rule enforced at the write boundary for any other caller.
 */
async changeMemoryGateHeadroomSetting(headroomMb: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_memory_gate_headroom_setting", { headroomMb }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Companion devices master toggle (OFF by default). Applies the runtime
 * change before persisting it (the update_microphone_mode rule, KB-027):
 * enabling starts the companion server and disabling stops it (finalizing
 * a live phone session first); a failed start throws so the settings store
 * rolls the toggle back instead of persisting an enabled state with no
 * server behind it.
 * 
 * No stop-the-server cleanup wraps the persist step, by invariant rather
 * than omission: this command's only Err is the failed start above, which
 * happens before any server exists, and settings::write_settings cannot
 * fail gracefully — it returns (), its store bootstrap is an expect and
 * its serialization an unwrap, the plugin's Store::set is infallible, and
 * the disk flush is a debounced background auto-save that discards its
 * errors. A persist failure is therefore panic-shaped and takes the whole
 * command down with it (no catch_unwind guards settings commands), so
 * there is no running-server-then-Err window for cleanup code to handle;
 * building any would be dead code.
 */
async changeCompanionDevicesSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_companion_devices_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Issue a fresh pairing token (rebound to the current LAN /24) and
 * restart the server if it is running, so the QR changes and phones
 * holding the old token are refused.
 */
async resetCompanionPairing() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reset_companion_pairing") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Snapshot for the settings panel: QR (SVG), URL, port, fingerprint,
 * connected devices, and any server error.
 */
async getCompanionStatus() : Promise<CompanionStatus> {
    return await TAURI_INVOKE("get_companion_status");
},
async changeAutoFallbackSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_auto_fallback_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeMenuBarModelTitleSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_menu_bar_model_title_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeShowHistoryModelSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_show_history_model_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAudioFeedbackVolumeSetting(volume: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_audio_feedback_volume_setting", { volume }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeSoundThemeSetting(theme: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_sound_theme_setting", { theme }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeThemeSetting(theme: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_theme_setting", { theme }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAccentColorSetting(accent: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_accent_color_setting", { accent }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeStartHiddenSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_start_hidden_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Launch-at-login toggle. KB-112: the login-item change is applied BEFORE
 * persisting and its failure propagates (the update_microphone_mode /
 * change_companion_devices_setting rule), so a failed enable rolls the
 * toggle back instead of leaving it on with no login item behind it - the
 * preference would only self-heal on the NEXT launch, and until then the
 * toggle lied about the app starting at login.
 */
async changeAutostartSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_autostart_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeTranslateToEnglishSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_translate_to_english_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeSelectedLanguageSetting(language: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_selected_language_setting", { language }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeOverlayPositionSetting(position: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_overlay_position_setting", { position }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeOverlayStyleSetting(style: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_overlay_style_setting", { style }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeDebugModeSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_debug_mode_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeWordCorrectionThresholdSetting(threshold: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_word_correction_threshold_setting", { threshold }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeExtraRecordingBufferSetting(ms: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_extra_recording_buffer_setting", { ms }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeStreamingReleaseTailSetting(ms: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_streaming_release_tail_setting", { ms }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changePasteDelayMsSetting(ms: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_paste_delay_ms_setting", { ms }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changePasteDelayAfterMsSetting(ms: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_paste_delay_after_ms_setting", { ms }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeReliablePasteSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_reliable_paste_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changePasteMethodSetting(method: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_paste_method_setting", { method }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAvailableTypingTools() : Promise<string[]> {
    return await TAURI_INVOKE("get_available_typing_tools");
},
async changeTypingToolSetting(tool: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_typing_tool_setting", { tool }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeExternalScriptPathSetting(path: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_external_script_path_setting", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeClipboardHandlingSetting(handling: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_clipboard_handling_setting", { handling }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAutoSubmitSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_auto_submit_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAutoSubmitKeySetting(key: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_auto_submit_key_setting", { key }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changePostProcessEnabledSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_post_process_enabled_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The Experimental master switch. KB-183/KB-145: it is also a kill switch
 * for the companion LAN server, whose ONLY UI control is unmounted while
 * experimental is off - so turning it OFF must stop a running server
 * (apply_enabled(false) finalizes a live phone session first), and turning
 * it back ON re-arms the server only when the stored companion toggle is
 * on, mirroring companion::init. The runtime change runs BEFORE persisting
 * (the update_microphone_mode rule); a failed re-arm is logged and badged
 * inside apply_enabled and does not veto the toggle, which gates more than
 * companion.
 */
async changeExperimentalEnabledSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_experimental_enabled_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changePostProcessBaseUrlSetting(providerId: string, baseUrl: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_post_process_base_url_setting", { providerId, baseUrl }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changePostProcessApiKeySetting(providerId: string, apiKey: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_post_process_api_key_setting", { providerId, apiKey }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changePostProcessModelSetting(providerId: string, model: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_post_process_model_setting", { providerId, model }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setPostProcessProvider(providerId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_post_process_provider", { providerId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async fetchPostProcessModels(providerId: string) : Promise<Result<string[], PostProcessModelError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fetch_post_process_models", { providerId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Test Connection: probe the selected provider and return a verdict the
 * settings panel renders (auth ok, latency, model reachable, or the
 * failure class). Cloud providers answer a model-list request and, when a
 * model is configured, a tiny completion on a hard 10 s budget; the local
 * provider's verdict is its selected model's downloaded state (no worker
 * spawn); Apple Intelligence maps to its availability check.
 */
async testPostProcessConnection(providerId: string) : Promise<Result<TestConnectionResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("test_post_process_connection", { providerId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addPostProcessPrompt(name: string, prompt: string) : Promise<Result<LLMPrompt, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_post_process_prompt", { name, prompt }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updatePostProcessPrompt(id: string, name: string, prompt: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_post_process_prompt", { id, name, prompt }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deletePostProcessPrompt(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_post_process_prompt", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Duplicate one template from the library: a fresh id, " copy" appended to
 * the name, `is_builtin` cleared (a duplicate is the operator's own even
 * when its source is a seed), and version restarted at 1. The source's
 * language/register/description ride along so the copy lands in the same
 * catalog bucket.
 */
async duplicatePostProcessPrompt(id: string) : Promise<Result<LLMPrompt, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("duplicate_post_process_prompt", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setPostProcessSelectedPrompt(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_post_process_selected_prompt", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Set the keep-warm window for the LOCAL post-process model, in seconds.
 * 0 (the default) is the exclusive swap of v1.3.0 (unload after every
 * generation); up to 600 keeps the worker resident that long after the
 * paste. Out-of-range values are rejected, never clamped.
 */
async changePostProcessLocalKeepWarmSecsSetting(seconds: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_post_process_local_keep_warm_secs_setting", { seconds }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The cycle command (the tray and any future surface share it). Advances
 * the selection and confirms the new template through the overlay notice.
 */
async cyclePostProcessPrompt() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cycle_post_process_prompt") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * "Test on my last transcript": run one template over the most recent
 * history entry's transcription through the exact engine lifecycle a
 * dictation uses (provider, model, shared validator, pp: record with the
 * `prompt_test` binding marker), WITHOUT pasting anything and WITHOUT
 * writing a history row. Typed errors: `no_history` when nothing exists
 * to test against, `prompt_not_found` for a dangling template id.
 */
async testPostProcessPrompt(promptId: string) : Promise<Result<PromptTestOutcome, TestPromptError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("test_post_process_prompt", { promptId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateCustomWords(words: string[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_custom_words", { words }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Temporarily unregister all bindings while the user is recording a
 * shortcut in the UI. This avoids firing actions while keys are recorded.
 */
async suspendAllBindings() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("suspend_all_bindings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Re-register all bindings after the user has finished recording.
 */
async resumeAllBindings() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resume_all_bindings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeMuteWhileRecordingSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_mute_while_recording_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAppendTrailingSpaceSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_append_trailing_space_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeLazyStreamCloseSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_lazy_stream_close_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeVadEnabledSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_vad_enabled_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeVadBackendSetting(backend: VadBackend) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_vad_backend_setting", { backend }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeFillerWordRemovalEnabledSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_filler_word_removal_enabled_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeSpokenPunctuationSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_spoken_punctuation_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAutoInterpretCommandsSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_auto_interpret_commands_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Write the edited command matrix. `Some(entries)` normalizes every
 * phrase and validates the table (empty phrases, over-length phrases,
 * duplicates across commands) before anything is persisted; the error
 * string surfaces in the UI toast. `None` resets to the built-in
 * defaults.
 */
async updateCommandMatrix(entries: CommandMatrixEntry[] | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_command_matrix", { entries }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The built-in default command matrix, read by the Settings editor so
 * the default phrases come from the backend instead of being duplicated
 * in TypeScript.
 */
async getDefaultCommandMatrix() : Promise<CommandMatrixEntry[]> {
    return await TAURI_INVOKE("get_default_command_matrix");
},
async changeTerminalPunctuationSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_terminal_punctuation_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeVoiceDeletionCommandsSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_voice_deletion_commands_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changePreviewBeforePasteSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_preview_before_paste_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Flip the delete-last-word master toggle and register or unregister its
 * binding to match, mirroring how the post-processing toggle drives its
 * shortcut. KB-198: apply-then-persist (the KB-027 rule) - the register
 * attempt runs BEFORE the toggle is persisted and its failure propagates
 * while ENABLING (Err rolls the settings store's toggle back) instead of
 * being discarded with `let _ =` (a chord duplicated onto a toggle-off
 * binding fails "already in use" and left the toggle reading on with a
 * dead key). The DISABLED direction stays infallible: unregistering is
 * best-effort teardown and must never trap the toggle off.
 */
async changeDeleteLastWordEnabledSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_delete_last_word_enabled_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Flip the undo master toggle and register or unregister its binding to
 * match. KB-198: apply-then-persist (the KB-027 rule) - the register
 * attempt runs BEFORE the toggle is persisted and its failure propagates
 * while ENABLING (Err rolls the settings store's toggle back) instead of
 * being discarded with `let _ =` (a chord duplicated onto a toggle-off
 * binding fails "already in use" and left the toggle reading on with a
 * dead key). The DISABLED direction stays infallible: unregistering is
 * best-effort teardown and must never trap the toggle off.
 */
async changeUndoEnabledSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_undo_enabled_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Flip the command-mode master toggle and register or unregister its
 * modifier binding to match. KB-198: apply-then-persist (the KB-027 rule)
 * - the register attempt runs BEFORE the toggle is persisted and its
 * failure propagates while ENABLING (Err rolls the settings store's
 * toggle back) instead of being discarded with `let _ =` (a chord
 * duplicated onto a toggle-off binding fails "already in use" and left
 * the toggle reading on with a dead key). The DISABLED direction stays
 * infallible: unregistering is best-effort teardown and must never trap
 * the toggle off.
 */
async changeCommandModeEnabledSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_command_mode_enabled_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeChineseScriptSetting(script: ChineseScript) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_chinese_script_setting", { script }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeNumberFormatSetting(format: NumberFormat) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_number_format_setting", { format }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeUpdatePolicySetting(policy: UpdatePolicy) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_update_policy_setting", { policy }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Whether the app is running from macOS's read-only translocation mount.
 * The frontend shows the move-to-Applications guidance when true; the
 * updater flow also uses it to make install failures actionable.
 */
async isAppTranslocated() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("is_app_translocated") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAppLanguageSetting(language: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_app_language_setting", { language }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeUpdateChecksSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_update_checks_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeShowWhatsNewOnUpdateSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_show_whats_new_on_update_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeWhatsNewLastSeenVersionSetting(version: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_whats_new_last_seen_version_setting", { version }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Change the keyboard implementation with runtime switching.
 * This will unregister all shortcuts from the old implementation,
 * validate shortcuts for the new implementation (resetting invalid ones to defaults),
 * and register them with the new implementation.
 */
async changeKeyboardImplementationSetting(implementation: string) : Promise<Result<ImplementationChangeResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_keyboard_implementation_setting", { implementation }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get the current keyboard implementation
 */
async getKeyboardImplementation() : Promise<string> {
    return await TAURI_INVOKE("get_keyboard_implementation");
},
async changeShowTrayIconSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_show_tray_icon_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeTranscribeAcceleratorSetting(accelerator: TranscribeAcceleratorSetting) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_transcribe_accelerator_setting", { accelerator }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeOrtAcceleratorSetting(accelerator: OrtAcceleratorSetting) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_ort_accelerator_setting", { accelerator }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeTranscribeGpuDevice(device: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_transcribe_gpu_device", { device }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Return which accelerators and GPU devices are available for this build.
 * 
 * First-call cost is dominated by enumerating GPU devices through the
 * transcribe.cpp Metal/Vulkan backend, which loads dynamic libraries and
 * probes hardware. Run it on the blocking pool so the webview thread
 * stays responsive - see also the startup pre-warm in `lib.rs`.
 */
async getAvailableAccelerators() : Promise<AvailableAccelerators> {
    return await TAURI_INVOKE("get_available_accelerators");
},
/**
 * Start key recording mode
 */
async startHandyKeysRecording(bindingId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_handy_keys_recording", { bindingId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Stop key recording mode
 */
async stopHandyKeysRecording() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_handy_keys_recording") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSecureInputStatus() : Promise<SecureInputStatus> {
    return await TAURI_INVOKE("get_secure_input_status");
},
async runKeyboardDiagnostic(durationSecs: number | null) : Promise<Result<KeyboardDiagnosticReport, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("run_keyboard_diagnostic", { durationSecs }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async showMainWindowCommand() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("show_main_window_command") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cancelOperation() : Promise<void> {
    await TAURI_INVOKE("cancel_operation");
},
async isPortable() : Promise<boolean> {
    return await TAURI_INVOKE("is_portable");
},
async isUpdateChecksLocked() : Promise<boolean> {
    return await TAURI_INVOKE("is_update_checks_locked");
},
async getAppDirPath() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_app_dir_path") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAppSettings() : Promise<Result<AppSettings, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_app_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getDefaultSettings() : Promise<Result<AppSettings, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_default_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getLogDirPath() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_log_dir_path") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setLogLevel(level: LogLevel) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_log_level", { level }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openRecordingsFolder() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_recordings_folder") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openLogDir() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_log_dir") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openAppDataDir() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_app_data_dir") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Check if Apple Intelligence is available on this device.
 * Called by the frontend when the user selects Apple Intelligence provider.
 */
async checkAppleIntelligenceAvailable() : Promise<boolean> {
    return await TAURI_INVOKE("check_apple_intelligence_available");
},
/**
 * Try to initialize Enigo (keyboard/mouse simulation).
 * On macOS, this will return an error if accessibility permissions are not granted.
 */
async initializeEnigo() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("initialize_enigo") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Initialize keyboard shortcuts.
 * On macOS, this should be called after accessibility permissions are granted.
 * This is idempotent - calling it multiple times is safe.
 */
async initializeShortcuts() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("initialize_shortcuts") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAvailableModels() : Promise<Result<ModelInfo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_available_models") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getModelInfo(modelId: string) : Promise<Result<ModelInfo | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_model_info", { modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async downloadModel(modelId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("download_model", { modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteModel(modelId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_model", { modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cancelDownload(modelId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_download", { modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setActiveModel(modelId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_active_model", { modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Persist the model selection WITHOUT loading it: the recovery path for a
 * first-run memory-gate refusal. Onboarding can complete with a downloaded
 * but unloaded model, and the first hotkey press loads it on demand (the
 * same on-demand load the "Immediately" unload timeout uses). Validations
 * mirror `switch_active_model`; on an unknown or undownloaded model the
 * settings are never touched. Nothing loads, so no loading-slot claim is
 * needed.
 */
async setActiveModelDeferred(modelId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_active_model_deferred", { modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getCurrentModel() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_current_model") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getTranscriptionModelStatus() : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_transcription_model_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async isModelLoading() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("is_model_loading") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Re-scan local sources (custom models dir + shared HF cache) for models added
 * since launch
 */
async rescanLocalModels() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rescan_local_models") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Resolve pasted Hugging Face input (a URL, `owner/repo`, or
 * `owner/repo/file.gguf`) into the repo's GGUF file list with sizes plus a
 * suggested file. Public repos only in v1: repos that cannot be read
 * anonymously come back as a structured error the UI can localize.
 */
async resolveHfModel(input: string) : Promise<Result<HfModelResolution, HfModelError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resolve_hf_model", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Download a specific file from a Hugging Face repo and register it, gated
 * on the GGUF architecture probe: an unsupported architecture is refused,
 * the blob deleted, and the error names the architecture and supported
 * families. Downloads nothing outside this explicit user action.
 */
async addHfModel(repoId: string, filename: string, revision: string | null) : Promise<Result<string, HfModelError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_hf_model", { repoId, filename, revision }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getLocalLlmModelStatus(modelId: string | null) : Promise<Result<LocalLlmModelStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_local_llm_model_status", { modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Download a post-process model through the standard ModelManager pipeline
 * (progress events included, into the dedicated llm-models cache), then
 * verify the sha256 ONCE against the trust anchor (spec 6.1, reviewer
 * finding R12): a mismatch deletes the file and errors so the entry reads
 * not-downloaded again (delete + re-download repairs any corruption).
 * `model_id: None` downloads the pinned builtin, exactly as before.
 */
async downloadLocalLlmModel(modelId: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("download_local_llm_model", { modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete a post-process model. Refuses with a transient error while a
 * post-process swap is running (L3): the swap may be about to restore a
 * voice model file this delete would remove. Deleting the SELECTED model
 * resets the selection to the pinned builtin so the engine never points at
 * a missing file.
 * 
 * DEVIATION 2 (flagged in the plan): unlike the voice-model delete path,
 * there is no unload-with-wait here. The LLM worker exists only inside a
 * swap, and the lease check above has already excluded swaps; outside a
 * swap there is never a resident LLM engine to unload.
 */
async deleteLocalLlmModel(modelId: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_local_llm_model", { modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Every post-process model (catalog + pinned + user-added) with its card
 * metadata and the selection flag. The settings section and the tray
 * submenu both read this; nothing else should (ASR surfaces keep using
 * `get_available_models`, which filters LocalLlm entries out).
 */
async getAvailableLlmModels() : Promise<Result<LlmModelEntry[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_available_llm_models") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setPostProcessLocalModel(modelId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_post_process_local_model", { modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Resolve pasted Hugging Face input for the POST-PROCESS add flow (same
 * listing shape as the voice flow; the suggested file prefers the smaller
 * LLM quants).
 */
async resolveLlmHfModel(input: string) : Promise<Result<HfModelResolution, HfModelError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resolve_llm_hf_model", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Download a specific GGUF from a Hugging Face repo and register it as a
 * post-process model, gated on the LLM architecture allowlist: an
 * unsupported architecture is refused, the blob deleted, and the error
 * names the architecture and supported families.
 */
async addLlmHfModel(repoId: string, filename: string, revision: string | null) : Promise<Result<string, HfModelError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_llm_hf_model", { repoId, filename, revision }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateMicrophoneMode(alwaysOn: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_microphone_mode", { alwaysOn }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getMicrophoneMode() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_microphone_mode") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getWindowsMicrophonePermissionStatus() : Promise<WindowsMicrophonePermissionStatus> {
    return await TAURI_INVOKE("get_windows_microphone_permission_status");
},
/**
 * Open the OS microphone privacy pane. On macOS this is the recovery path
 * for a user who denied the mic in the system dialog: the TCC state can
 * only be flipped from System Settings > Privacy & Security > Microphone,
 * so the mic-denial guidance card links here.
 */
async openMicrophonePrivacySettings() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_microphone_privacy_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAvailableMicrophones() : Promise<Result<AudioDevice[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_available_microphones") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setSelectedMicrophone(deviceName: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_selected_microphone", { deviceName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSelectedMicrophone() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_selected_microphone") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAvailableOutputDevices() : Promise<Result<AudioDevice[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_available_output_devices") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setSelectedOutputDevice(deviceName: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_selected_output_device", { deviceName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSelectedOutputDevice() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_selected_output_device") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async playTestSound(soundType: string) : Promise<void> {
    await TAURI_INVOKE("play_test_sound", { soundType });
},
async checkCustomSounds() : Promise<CustomSounds> {
    return await TAURI_INVOKE("check_custom_sounds");
},
async setClamshellMicrophone(deviceName: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_clamshell_microphone", { deviceName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getClamshellMicrophone() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_clamshell_microphone") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async isRecording() : Promise<boolean> {
    return await TAURI_INVOKE("is_recording");
},
async getMicrophoneChannels(deviceName: string) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_microphone_channels", { deviceName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setSelectedChannel(channel: number | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_selected_channel", { channel }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setModelUnloadTimeout(timeout: ModelUnloadTimeout) : Promise<void> {
    await TAURI_INVOKE("set_model_unload_timeout", { timeout });
},
/**
 * Set the idle-unload timeout to a custom seconds value (the Settings
 * numeric field and any future UI that speaks seconds). Rejects
 * out-of-range values instead of clamping so a UI bug can't silently write
 * a 3-second or 30-day timeout the user never saw.
 */
async setModelUnloadTimeoutCustomSeconds(seconds: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_model_unload_timeout_custom_seconds", { seconds }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Set the total-request timeout for cloud post-process calls, in seconds.
 * Rejects out-of-range values instead of clamping so a UI bug can't
 * silently write a 1-second or 10-minute timeout the user never saw.
 */
async setPostProcessTimeout(seconds: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_post_process_timeout", { seconds }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Set the per-provider override of the post-process timeout, in seconds.
 * Same inclusive bounds as the global setting (rejecting out-of-range
 * values instead of clamping); the provider's requests then run under
 * this value instead of its class default. The reset command below
 * removes the override; a stored 0 also resolves to the class default.
 */
async setPostProcessTimeoutForProvider(providerId: string, seconds: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_post_process_timeout_for_provider", { providerId, seconds }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Remove the per-provider post-process timeout override: the provider's
 * requests resolve through its class default again (Groq/Cerebras 30s,
 * the others 60s), which is what the settings row shows as the reset
 * target.
 */
async resetPostProcessTimeoutForProvider(providerId: string) : Promise<void> {
    await TAURI_INVOKE("reset_post_process_timeout_for_provider", { providerId });
},
async getModelLoadStatus() : Promise<Result<ModelLoadStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_model_load_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async unloadModelManually() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("unload_model_manually") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async logUpdateDecision(stage: string, detail: string | null) : Promise<void> {
    await TAURI_INVOKE("log_update_decision", { stage, detail });
},
async getHistoryEntries(cursor: number | null, limit: number | null) : Promise<Result<PaginatedHistory, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_history_entries", { cursor, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async toggleHistoryEntrySaved(id: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("toggle_history_entry_saved", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAudioFilePath(fileName: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_audio_file_path", { fileName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteHistoryEntry(id: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_history_entry", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async retryHistoryEntryTranscription(id: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("retry_history_entry_transcription", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateHistoryLimit(limit: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_history_limit", { limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateRecordingRetentionPeriod(period: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_recording_retention_period", { period }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The Tauri command the Debug tab's table calls. Returns the most recent
 * runs, newest first.
 */
async getPostProcessRuns(limit: number | null) : Promise<Result<PostProcessRunRecord[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_post_process_runs", { limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Checks if the Mac is a laptop by detecting battery presence
 * 
 * This uses pmset to check for battery information.
 * Returns true if a battery is detected (laptop), false otherwise (desktop)
 */
async isLaptop() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("is_laptop") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
historyUpdatePayload: HistoryUpdatePayload,
overlayNoticeEvent: OverlayNoticeEvent,
postProcessRunEvent: PostProcessRunEvent,
postProcessSkipEvent: PostProcessSkipEvent,
streamPhaseEvent: StreamPhaseEvent,
streamTextEvent: StreamTextEvent
}>({
historyUpdatePayload: "history-update-payload",
overlayNoticeEvent: "overlay-notice-event",
postProcessRunEvent: "post-process-run-event",
postProcessSkipEvent: "post-process-skip-event",
streamPhaseEvent: "stream-phase-event",
streamTextEvent: "stream-text-event"
})

/** user-defined constants **/



/** user-defined types **/

/**
 * The container-level `serde(default)` (backed by the `Default` impl below)
 * guarantees every field - including ones added in the future - falls back to
 * its `get_default_settings()` value when missing from a stored settings
 * object, so a partial store can never fail the whole load (#1619).
 * Field-level defaults below take precedence where present.
 */
export type AppSettings = { 
/**
 * Internal settings schema marker for one-time migrations. Fresh installs
 * start at the current version; existing stores missing this key are
 * treated as version 0 and migrated forward.
 */
settings_schema_version?: number; 
/**
 * Defaults to empty on partial stores; the load path merges in the
 * default bindings for any missing keys before the settings are used.
 */
bindings?: Partial<{ [key in string]: ShortcutBinding }>; 
/**
 * Replaces the pre-0.10 `push_to_talk` bool; stores missing this key are
 * migrated from it in `apply_settings_migrations`.
 */
shortcut_activation?: ShortcutActivation; 
/**
 * Hold-or-toggle only: a press held at least this long is push-to-talk,
 * anything shorter is a tap that locks recording on.
 */
hold_threshold_ms?: number; audio_feedback?: boolean; audio_feedback_volume?: number; sound_theme?: SoundTheme; start_hidden?: boolean; autostart_enabled?: boolean; update_checks_enabled?: boolean; 
/**
 * What the automatic startup check may do when it finds an update; see
 * [`UpdatePolicy`]. Manual checks (tray item, footer, About button)
 * always ask regardless of this setting.
 */
update_policy?: UpdatePolicy; show_whats_new_on_update?: boolean; 
/**
 * The app version whose What's New the user has already seen. Fresh installs
 * default to the current version (nothing is "new" to them). Existing users
 * upgrading from before this key existed are blanked by the migration so they
 * see the current release's notes - see `apply_settings_migrations`.
 */
whats_new_last_seen_version?: string; selected_model?: string; onboarding_completed?: boolean; always_on_microphone?: boolean; selected_microphone?: string | null; 
/**
 * Which input channel to use on the selected microphone device.
 * None means "average all channels" (original behavior).
 */
selected_channel?: number | null; clamshell_microphone?: string | null; selected_output_device?: string | null; translate_to_english?: boolean; selected_language?: string; overlay_position?: OverlayPosition; debug_mode?: boolean; log_level?: LogLevel; 
/**
 * Built-in dictionary seed so the speech models stop mishearing the app
 * name ("woksbar", "woxbar", "worksbar" and similar). Applies only when
 * the stored settings have no `custom_words` key (fresh installs, or
 * stores written before the setting existed). A user who edits the list,
 * including deleting the seed, has an explicit key persisted and is never
 * clobbered or re-seeded.
 */
custom_words?: string[]; model_unload_timeout?: ModelUnloadTimeout; memory_pressure_guard?: boolean; 
/**
 * Memory safety margin for the memory-pressure gate, in MB: free RAM
 * kept above the model's forecast footprint before the gate refuses a
 * load. 0 (the default) means the forecast alone must fit. A
 * user-chosen value is 0 or at least 5 MB (the settings UI rejects 1-4
 * with a validation message); a stale stored 1-4 normalizes to 0 on
 * load as a store guard.
 */
memory_gate_headroom_mb?: number; 
/**
 * When the memory-pressure guard refuses the selected model AND this is
 * on, automatically load the best already-downloaded model that fits
 * free RAM instead of failing the dictation. Off reproduces the plain
 * refuse-with-toast behavior.
 */
auto_fallback?: boolean; 
/**
 * Show the resident model + compact RAM as the macOS menu-bar title
 * (next to the tray icon). Off never produces a title, clearing any
 * currently-displayed one.
 */
menu_bar_model_title?: boolean; word_correction_threshold?: number; history_limit?: number; 
/**
 * Show the compact per-entry model badge in the History list.
 */
show_history_model?: boolean; recording_retention_period?: RecordingRetentionPeriod; paste_method?: PasteMethod; clipboard_handling?: ClipboardHandling; auto_submit?: boolean; auto_submit_key?: AutoSubmitKey; post_process_enabled?: boolean; 
/**
 * Total-request timeout for cloud post-process calls, in seconds.
 * Bounds a wedged endpoint (one that accepts the connection but never
 * responds) so the stop pipeline returns to Idle instead of hanging
 * with only the tray Cancel as an escape. Applies to both the chat
 * completion and the model-list requests.
 */
post_process_timeout_secs?: number; 
/**
 * Per-provider user overrides of the post-process timeout, keyed by
 * provider id. Empty (the default) means every provider resolves
 * through its class default (see
 * [`PostProcessProvider::default_timeout_secs`]) and then the global
 * `post_process_timeout_secs`; a stored 0 resolves the same way (the
 * reset target), never "no timeout".
 */
post_process_timeouts?: Partial<{ [key in string]: number }>; 
/**
 * Keep-warm window for the LOCAL post-process model, in seconds. 0
 * (the default) is exactly today's behavior: the swap runner unloads
 * the worker after every generation and restores the voice model (the
 * L2 exclusive swap). When > 0, the runner holds the worker resident
 * for the window AFTER the paste, polling the dictation-wins triggers
 * and an evict request; any voice model load evicts it first.
 */
post_process_local_keep_warm_secs?: number; post_process_provider_id?: string; 
/**
 * The registry id of the local post-process model the swap runner loads
 * (catalog entry or the pinned builtin). Defaults to the pinned
 * Qwen3-0.6B, so stores written before the LLM catalog existed keep
 * exactly their prior behavior without a migration.
 */
post_process_local_model_id?: string; post_process_providers?: PostProcessProvider[]; post_process_api_keys?: SecretMap; post_process_models?: Partial<{ [key in string]: string }>; 
/**
 * Last successfully fetched model list per provider id (see
 * [`CachedModelList`]). Empty on stores written before the cache
 * existed; the store hydrates the dropdown from it on load. Cleared
 * for a provider when its base URL changes (a different endpoint
 * serves a different list).
 */
post_process_model_lists?: Partial<{ [key in string]: CachedModelList }>; post_process_prompts?: LLMPrompt[]; post_process_selected_prompt_id?: string | null; 
/**
 * One-time marker for the local-default post-process migration (spec
 * 5.2): absent on legacy stores (the migration fires once), true on
 * every store the migration or a fresh install has written. The only
 * new field this feature adds; the schema-version ladder is
 * deliberately NOT used.
 */
post_process_local_default_migrated?: boolean; mute_while_recording?: boolean; append_trailing_space?: boolean; app_language?: string; theme?: Theme; accent_color?: string; experimental_enabled?: boolean; lazy_stream_close?: boolean; keyboard_implementation?: KeyboardImplementation; show_tray_icon?: boolean; paste_delay_ms?: number; paste_delay_after_ms?: number; 
/**
 * Debug-gated ("beta") receipt-sequenced paste: restore the clipboard only
 * after the target app actually reads the transcript, instead of after a
 * fixed delay. See `paste_tx`. macOS and Windows only.
 */
reliable_paste?: boolean; typing_tool?: TypingTool; external_script_path?: string | null; filler_word_removal_enabled?: boolean; custom_filler_words?: string[] | null; 
/**
 * The edited command matrix: one row per command with its spoken
 * phrases. None means the built-in defaults; Some means the operator
 * edited the table and the full edited list is persisted (the
 * precedent of `custom_words`). Consequence, accepted: an operator
 * who edited the matrix does not automatically gain default phrases
 * added in later versions; clearing the setting back to None resets.
 */
command_phrases?: CommandMatrixEntry[] | null; 
/**
 * Convert standalone spoken punctuation tokens ("comma", "full stop",
 * "question mark", ...) into real punctuation before custom-word
 * correction.
 */
spoken_punctuation?: boolean; 
/**
 * Master gate over the two spoken-command passes in NORMAL dictation
 * (spoken punctuation and voice deletion): ON is exactly today's
 * behavior; OFF leaves command words as plain transcribed words. The
 * command-mode modifier is a separate surface and is NOT gated by
 * this toggle.
 */
auto_interpret_commands?: boolean; 
/**
 * Ensure every transcript ends with terminal punctuation: "?" when the
 * first word is an interrogative, otherwise ".".
 */
terminal_punctuation?: boolean; 
/**
 * Voice deletion commands: "scratch that" / "delete that" remove the
 * preceding word, "delete last N words" removes several, "delete line"
 * clears the trailing line, and "delete everything" /
 * "scratch everything" clears the transcription.
 */
voice_deletion_commands?: boolean; 
/**
 * Briefly show the final transcription in the recording overlay before
 * it is pasted (~1.2s). Gives non-streaming (batch) models the same
 * final-text confirmation the live overlay gives streaming models; off
 * pastes immediately as before.
 */
preview_before_paste?: boolean; 
/**
 * Master toggle for the assignable "delete last word" hotkey action.
 * The action also ships unbound, so it stays inert until the operator
 * binds a key for it.
 */
delete_last_word_enabled?: boolean; 
/**
 * Master toggle for the assignable "undo" hotkey action. Like the
 * delete-word action it ships unbound and stays inert until a key is
 * bound.
 */
undo_enabled?: boolean; 
/**
 * Master toggle for command mode: the assignable during-dictation
 * modifier that switches a live dictation session into command
 * interpretation (punctuation, line breaks, delete word/line editing
 * the session buffer). Ships unbound, so it stays inert until the
 * operator binds a key.
 */
command_mode_enabled?: boolean; 
/**
 * Fresh installs default from the OS locale; existing stores are migrated
 * in `apply_settings_migrations`.
 */
chinese_script?: ChineseScript; 
/**
 * Spoken number formatting (number_format.rs): digits for the default
 * fix, smart for prose-friendly extras, as_transcribed for the exact
 * 1.1.0 behavior. The plain serde default (Digits) also covers legacy
 * stores that predate the key.
 */
number_format?: NumberFormat; transcribe_accelerator?: TranscribeAcceleratorSetting; ort_accelerator?: OrtAcceleratorSetting; 
/**
 * Stable transcribe.cpp device selector. This is derived from the backend's
 * `device_id` when available (or its name for backends such as Metal),
 * never from the process-local device registry index.
 */
transcribe_gpu_device?: string | null; extra_recording_buffer_ms?: number; 
/**
 * Post-release capture floor for STREAMING sessions only: releasing
 * the hotkey the instant a spoken command word ends otherwise
 * truncates its tail and the command silently fails. The stop path
 * uses max(extra_recording_buffer_ms, streaming_release_tail_ms) when
 * the recording ran with an active stream; batch sessions are
 * untouched. 0 restores the old no-tail behavior exactly.
 */
streaming_release_tail_ms?: number; vad_enabled?: boolean; 
/**
 * Experimental detector implementation. Silero remains the stable default.
 */
vad_backend?: VadBackend; 
/**
 * Which recording overlay to show: None / Minimal / Live. Streaming mode is
 * not gated on this - that follows model capability. Migrated from the old
 * `overlay_position` (position `none` → style `None`).
 */
overlay_style?: OverlayStyle; 
/**
 * Companion devices: use a phone/tablet on the same Wi-Fi as a remote
 * microphone and push-to-talk trigger, with this Mac as the engine.
 * OFF by default - the off path leaves no listener, no threads, and
 * the local recorder path untouched.
 */
companion_devices_enabled?: boolean; 
/**
 * Port for the companion TLS/WebSocket server on the LAN interface.
 */
companion_port?: number; 
/**
 * 128-bit hex pairing token, generated on enable/reset and bound to
 * the advertised interface's /24 subnet. A peer from a different
 * subnet is refused with a re-pair notice.
 */
companion_pairing_token?: string | null; 
/**
 * The /24 (as "a.b.c.0/24") the pairing token was issued for.
 */
companion_pairing_subnet?: string | null; 
/**
 * Name of the last device that completed a hello handshake.
 */
companion_last_device?: string | null }
export type AudioDevice = { index: string; name: string; is_default: boolean }
export type AutoSubmitKey = "enter" | "ctrl_enter" | "cmd_enter"
export type AvailableAccelerators = { transcribe: string[]; ort: string[]; gpu_devices: GpuDeviceOption[] }
export type BindingResponse = { success: boolean; binding: ShortcutBinding | null; error: string | null }
/**
 * The last successfully fetched model list for one provider, persisted so
 * reopening the settings panel shows the dropdown instantly (and offline).
 * Only successful fetches are written; failures never clobber a good list.
 */
export type CachedModelList = { models: string[]; 
/**
 * Unix seconds (UTC) of the successful fetch, shown as a fetched-at
 * hint next to the dropdown.
 */
fetched_at_unix: number }
/**
 * Script applied to Mandarin and Cantonese output. Other languages are never
 * converted.
 */
export type ChineseScript = 
/**
 * Keep whatever script the model produced.
 */
"as_transcribed" | "simplified" | "traditional"
export type ClipboardHandling = "dont_modify" | "copy_to_clipboard"
/**
 * One command of the matrix. Thirty fixed commands; only their PHRASES
 * are editable. camelCase serde names are the persisted and TS contract.
 */
export type CommandId = "period" | "comma" | "questionMark" | "exclamation" | "colon" | "semicolon" | "dash" | "newLine" | "newParagraph" | "atSign" | "hash" | "dollarSign" | "percent" | "star" | "ampersand" | "caret" | "openParen" | "closeParen" | "openBracket" | "closeBracket" | "openBrace" | "closeBrace" | "slash" | "backslash" | "pipe" | "deleteWord" | "deleteLine" | "clearAll" | "undo" | "paste"
/**
 * One matrix row: a command and its editable spoken phrases.
 */
export type CommandMatrixEntry = { command: CommandId; phrases: string[] }
/**
 * The status snapshot the settings panel renders (QR, URL, devices,
 * fingerprint, error).
 */
export type CompanionStatus = { enabled: boolean; running: boolean; supported: boolean; url: string | null; port: number; qr_svg: string | null; fingerprint: string | null; token: string | null; subnet: string | null; last_device: string | null; devices: string[]; error: string | null }
export type CustomSounds = { start: boolean; stop: boolean }
export type EngineType = 
/**
 * Any GGML/GGUF model loaded through transcribe-cpp (Whisper, Parakeet,
 * Voxtral, Qwen3-ASR, Nemotron, …). The architecture is auto-detected from
 * the file, so this one variant covers the whole transcribe-cpp family.
 */
"TranscribeCpp" | "Parakeet" | "Moonshine" | "MoonshineStreaming" | "SenseVoice" | "GigaAM" | "Canary" | "Cohere" | 
/**
 * The local post-process LLM (Qwen3-0.6B GGUF). Loaded only by the
 * local post-process engine's worker process, never an ASR engine:
 * every ASR path (load dispatch, fallback list, model pickers) refuses
 * or filters it. Registered in the ModelManager so the download,
 * delete, and status lifecycle is shared with voice models.
 */
"LocalLlm"
export type GpuDeviceOption = { id: string; name: string; total_vram_mb: number }
/**
 * Structured failure kinds for the add-from-Hugging-Face flow, so the
 * frontend can localize each instead of showing raw error strings.
 */
export type HfModelError = 
/**
 * The pasted text is not a repo URL, owner/name, or owner/name/file.gguf.
 */
{ InvalidInput: { detail: string } } | { RepoNotFound: { repo_id: string } } | 
/**
 * The repo cannot be read anonymously: to an unauthenticated caller the
 * Hub answers 401 identically for a repo that does not exist and one
 * that is private or gated, so the two cannot be told apart. v1 supports
 * public repos only (no token is ever sent).
 */
{ Inaccessible: { repo_id: string } } | { FileNotFound: { repo_id: string; filename: string } } | { NoGgufFiles: { repo_id: string } } | { Network: { detail: string } } | { DownloadFailed: { detail: string } } | 
/**
 * The user cancelled the download (the partial is kept for resume).
 */
"Cancelled" | 
/**
 * The downloaded GGUF's `general.architecture` is not one the engines
 * support; nothing was registered and the blob was deleted.
 */
{ UnsupportedArchitecture: { architecture: string | null; supported: string[] } }
/**
 * The repo listing handed to the UI when the user's input resolves.
 */
export type HfModelResolution = { repo_id: string; 
/**
 * Commit sha the listing was read at. Pinning the download to it keeps
 * the fetched bytes identical to the listed sizes; `None` falls back to
 * `main`.
 */
revision: string | null; 
/**
 * Every `.gguf` in the repo, sorted by filename for display.
 */
files: HfRepoFile[]; 
/**
 * The file to download when the user does not choose one: the input's
 * own file, else the quant preference below.
 */
suggested_filename: string }
/**
 * One `.gguf` file inside a Hugging Face repo, as listed by the metadata API.
 */
export type HfRepoFile = { 
/**
 * Path within the repo (subfolders included).
 */
filename: string; 
/**
 * Blob size in bytes when the API reported it.
 */
size_bytes: number | null }
export type HistoryEntry = { id: number; file_name: string; timestamp: number; saved: boolean; title: string; transcription_text: string; post_processed_text: string | null; post_process_prompt: string | null; post_process_requested: boolean; 
/**
 * Model id that actually produced `transcription_text` (the resident
 * model at transcription time - after a RAM auto-fallback this is the
 * fallback). `None` for pre-migration entries or when the model was
 * unknown (e.g. a failed transcription saved for retry).
 */
model_id: string | null; 
/**
 * The pp: run summary (the post-process lifecycle, WS3): which
 * provider/model/prompt polished this entry, how the run ended
 * (`applied` | `skipped:<reason>` | `failed:<class>`), and its
 * latency. `None` for pre-cycle rows and entries whose dictation ran
 * without post-processing.
 */
post_process_provider: string | null; post_process_model: string | null; post_process_prompt_id: string | null; post_process_outcome: string | null; post_process_latency_ms: number | null }
export type HistoryUpdatePayload = { action: "added"; entry: HistoryEntry } | { action: "updated"; entry: HistoryEntry } | { action: "deleted"; id: number } | { action: "toggled"; id: number }
/**
 * Result of changing keyboard implementation
 */
export type ImplementationChangeResult = { success: boolean; 
/**
 * List of binding IDs that were reset to defaults due to incompatibility
 */
reset_bindings: string[] }
export type KeyboardDiagnosticReport = { secure_input_enabled: boolean; culprit_pid: number | null; culprit_name: string | null; 
/**
 * Counts only - key identity is deliberately never captured.
 */
key_down: number; key_up: number; flags_changed: number; mouse: number; duration_ms: number }
export type KeyboardImplementation = "tauri" | "handy_keys"
/**
 * One template in the post-process prompt library. The three original
 * fields (id, name, prompt) are the pre-library store shape; every newer
 * field carries `#[serde(default)]` so stores written before the library
 * existed load unchanged and are upgraded by `ensure_post_process_defaults`
 * instead of a schema bump.
 */
export type LLMPrompt = { id: string; name: string; prompt: string; 
/**
 * BCP-47 tag of the output language this template keeps, or "auto" to
 * follow whatever language was spoken.
 */
language?: string; register?: PromptRegister; 
/**
 * One-line catalog copy. The built-in seeds ship their description
 * translated through the frontend locale files; this stored value is
 * the English fallback.
 */
description?: string; 
/**
 * True for the seeded templates. Built-ins can be edited in place
 * (the edit bumps `version`, which stops the seeding migration from
 * ever touching them again); duplicates and user creations are false.
 */
is_builtin?: boolean; 
/**
 * Bumped on every user edit. 0 marks a store written before the
 * library existed (never touched by this build); seeds and fresh
 * creations start at 1.
 */
version?: number }
/**
 * One post-process model as the settings section and tray see it: the
 * shared [`ModelInfo`] plus the LLM-specific card fields the ASR shape does
 * not carry.
 */
export type LlmModelEntry = { info: ModelInfo; 
/**
 * Quantization of the surfaced file ("Q4_K_M"), when known.
 */
quant: string; 
/**
 * Context window the swap runner allocates for this model.
 */
context_tokens: number; 
/**
 * Display publisher ("Qwen", "bartowski"), when known.
 */
publisher: string; 
/**
 * Whether this is the model the post-process engine runs.
 */
selected: boolean }
/**
 * Status snapshot for one post-process model row (spec 6.2). `model_id:
 * None` reads the pinned builtin, the shape the original settings row was
 * built on.
 */
export type LocalLlmModelStatus = { downloaded: boolean; downloading: boolean; size_mb: number; 
/**
 * 0 to 100 while downloading (partial bytes over the total); 0 or 100
 * otherwise.
 */
progress: number }
export type LogLevel = "trace" | "debug" | "info" | "warn" | "error"
export type ModelInfo = { id: string; name: string; description: string; filename: string; source: ModelSource; size_mb: number; is_downloaded: boolean; is_downloading: boolean; partial_size: number; is_directory: boolean; engine_type: EngineType; accuracy_score: number; speed_score: number; supports_translation: boolean; is_recommended: boolean; supported_languages: string[]; supports_language_selection: boolean; is_custom: boolean; supports_streaming: boolean; supports_language_detection: boolean }
export type ModelLoadStatus = { is_loaded: boolean; current_model: string | null }
/**
 * Where a model comes from and how Handy obtains it - the routing discriminant
 * for downloading and on-disk resolution.
 */
export type ModelSource = 
/**
 * Direct HTTP download from a URL (current blob.handy.computer hosting).
 */
{ Url: { url: string; 
/**
 * Expected SHA-256 for integrity verification; `None` skips it.
 */
sha256: string | null } } | 
/**
 * A file inside a Hugging Face Hub repo, fetched via hf-hub into the shared
 * HF cache (so other tools reuse it). The file within the repo is
 * [`ModelInfo::filename`].
 */
{ HuggingFace: { repo_id: string; revision: string } } | 
/**
 * Already present on disk - a user-provided custom model, or one discovered
 * in a shared cache. Nothing to download.
 */
"Local"
export type ModelUnloadTimeout = "never" | "immediately" | "min_2" | "min_5" | "min_10" | "min_15" | "hour_1" | "sec_15" | 
/**
 * User-entered idle timeout in seconds (tray "Unload After → Custom…"
 * and the Settings numeric field). Serialized as
 * `{"custom":{"seconds":N}}`; the fixed variants above keep their
 * string wire format, so stored settings are unaffected.
 */
{ custom: { seconds: number } }
/**
 * How spoken number words are written in the transcript. Post-model and
 * deterministic (number_format.rs); `as_transcribed` restores the 1.1.0
 * behavior byte-for-byte. The release default is `digits` because the
 * words-not-digits transcripts operators hit (Parakeet-class engines
 * spell every number out) must stop happening out of the box: old stores
 * without the key deserialize to `digits` via the derived default, and
 * `NumberFormat::default()` agrees (no constructed/derived split).
 */
export type NumberFormat = "as_transcribed" | "digits" | "smart"
export type OrtAcceleratorSetting = "auto" | "cpu" | "cuda" | "directml" | "rocm"
/**
 * One feedback notice for the overlay-first user: something went wrong (or
 * fell back) during a dictation and the person living in the overlay must
 * hear about it through the overlay, not only through a toast in a window
 * they never open.
 * 
 * Display rule, stated once: the overlay card renders the notice row ONLY
 * while the card is already visible; when the overlay is hidden (including
 * `OverlayStyle::None`, where the show path no-ops) the channel is the
 * error sound plus the existing main-window toast and the file log. The
 * backend NEVER force-shows the overlay for a notice, so no flashed pills.
 */
export type OverlayNoticeEvent = { kind: OverlayNoticeKind; 
/**
 * Stable machine code; the frontend maps it to a localized message.
 */
code: string; 
/**
 * Diagnostic detail (error text, model names). Optional by design.
 */
detail?: string | null; 
/**
 * Whether the overlay card could render this notice at emit time
 * (`overlay_style` not None AND the overlay window visible). When
 * false the card row is unreachable, so the frontend routes the
 * notice to a macOS notification instead of a surface nobody sees
 * (KB-020: hidden-card notices were invisible on every surface).
 */
card_visible: boolean }
/**
 * Tone of an [`OverlayNoticeEvent`]: failures are errors, expected or
 * recoverable conditions are info. Errors carry the error sound; info does
 * not (an expected skip must not beep on every dictation).
 */
export type OverlayNoticeKind = "error" | "info"
export type OverlayPosition = "top" | "bottom"
/**
 * Which recording overlay to display. `Minimal` and `Live` share one base
 * (the pill); `Live` grows into the panel that shows live transcription text.
 * `None` hides the overlay entirely. Decoupled from whether the model runs in
 * streaming mode (that is driven purely by model capability).
 */
export type OverlayStyle = "none" | "minimal" | "live"
export type PaginatedHistory = { entries: HistoryEntry[]; has_more: boolean }
export type PasteMethod = "ctrl_v" | "direct" | "none" | "shift_insert" | "ctrl_shift_v" | "external_script"
export type PermissionAccess = "allowed" | "denied" | "unknown"
/**
 * Which engine kind produced a run. Rides the `requested` line so a log
 * reader can tell the three paths apart before any other field.
 */
export type PostProcessEngineKind = "cloud" | "local" | "apple_intelligence"
/**
 * The engine phase facts (local engine): how long the model load took,
 * whether the model was already resident (it never is today - the swap
 * spawns a fresh worker - but the field is the honest place for a future
 * keep-alive), and how long the run waited on the swap machinery (lease,
 * slot, gate, voice unload) before the load began. Cloud runs carry None
 * for all three.
 */
export type PostProcessEnginePhase = { model_load_ms: number | null; cache_hit: boolean | null; swap_wait_ms: number | null }
/**
 * Failure classes shared across the post-process surface: the Test
 * Connection verdict line here, and the pp: observability lifecycle that
 * classifies every failed run. The wire values are stable tokens the UI
 * prints verbatim (auth, network, timeout, context_length,
 * output_invalid, oom, cancelled), so they are part of the contract with
 * the frontend and must never be renamed.
 */
export type PostProcessFailureClass = "auth" | "network" | "timeout" | "context_length" | "output_invalid" | "oom" | "cancelled"
/**
 * The generation phase facts: wall-clock ms and retry count (a structured
 * attempt that fell back to the legacy prompt shape counts as one retry).
 */
export type PostProcessGenerationPhase = { ms: number | null; retries: number | null }
/**
 * Structured error for the cloud model-list path (and the connection
 * probe), replacing the bare String `fetch_post_process_models` used to
 * return. The tag/kind is the failure class the UI prints; `detail`
 * carries the sanitized diagnostics (never key material, never response
 * payloads that could quote transcription content).
 */
export type PostProcessModelError = { kind: "auth"; detail: string } | { kind: "network"; detail: string } | { kind: "timeout"; detail: string } | { kind: "parse"; detail: string } | { kind: "other"; detail: string }
/**
 * How one run ended.
 */
export type PostProcessOutcome = 
/**
 * The processed text was pasted.
 */
{ kind: "applied" } | 
/**
 * The engine never produced output (expected, recoverable); the raw
 * transcript was used. Carries the local-engine skip vocabulary.
 */
{ kind: "skipped"; reason: SkipReason } | 
/**
 * The engine tried and failed; the raw transcript was used. Carries
 * the failure class.
 */
{ kind: "failed"; class: PostProcessFailureClass }
export type PostProcessProvider = { id: string; label: string; base_url: string; allow_base_url_edit?: boolean; models_endpoint?: string | null; supports_structured_output?: boolean; 
/**
 * The provider class's default total-request timeout, in seconds.
 * Fast inference hosts (Groq, Cerebras) default tighter (30) than the
 * general 60; a per-provider user override
 * (`post_process_timeouts`) beats it, and 0 falls through to the
 * global `post_process_timeout_secs` at resolution time.
 */
default_timeout_secs?: number }
/**
 * Emitted once per lifecycle phase. The overlay window drives its
 * "Polishing (model) 1.8s" chip off Requested/Outcome; the main window
 * toasts failure classes off Outcome.
 */
export type PostProcessRunEvent = { run_id: number; phase: PostProcessRunPhase; payload: PostProcessRunPayload }
/**
 * The per-phase event payload. Only the fields belonging to the event's
 * phase are populated; the rest stay None.
 */
export type PostProcessRunPayload = { binding: string | null; engine: PostProcessEngineKind | null; provider_id: string | null; model: string | null; prompt_name: string | null; model_load_ms: number | null; cache_hit: boolean | null; swap_wait_ms: number | null; generation_ms: number | null; retries: number | null; outcome: PostProcessOutcome | null; chars_in: number | null; chars_out: number | null; total_ms: number | null }
/**
 * The lifecycle phases, in order. Exactly one `pp:` line and one
 * [`PostProcessRunEvent`] per phase per run.
 */
export type PostProcessRunPhase = "requested" | "engine" | "generation" | "outcome"
/**
 * One completed (or in-flight) post-process run. Everything the Debug
 * table shows and everything the copy button returns lives here.
 */
export type PostProcessRunRecord = { 
/**
 * Monotonic per-app-launch id, starting at 1.
 */
run_id: number; 
/**
 * Unix epoch milliseconds (UTC) when the requested phase fired.
 */
started_at_unix_ms: number; binding: string; engine: PostProcessEngineKind; provider_id: string; model: string; prompt_id: string | null; prompt_name: string | null; 
/**
 * The prompt template's version token, when the prompt carries one.
 */
prompt_version: string | null; 
/**
 * The template's target language (the per-language prompt library),
 * when the prompt carries one.
 */
template_language: string | null; phases_engine: PostProcessEnginePhase; phases_generation: PostProcessGenerationPhase; 
/**
 * `None` while the run is still live.
 */
outcome: PostProcessOutcome | null; chars_in: number | null; chars_out: number | null; 
/**
 * chars_out / chars_in (how much of the transcript survived), None
 * when chars_in is 0 or the run produced no output.
 */
changed_ratio: number | null; total_ms: number | null; 
/**
 * The run's own captured `pp:` lines, in order. This is exactly what
 * the Debug table's copy button puts on the clipboard.
 */
log_lines: string[] }
/**
 * Emitted when a local post-process pass fell back to the raw transcript
 * (spec 7.3). The frontend toasts it at most once per reason per app
 * session; the memory_gate variant carries the formatted refusal numbers
 * in `detail`.
 */
export type PostProcessSkipEvent = { reason: SkipReason; detail?: string | null }
/**
 * The register (tone) a prompt template is written for. Part of the
 * template catalog's metadata; the settings list and the selected-template
 * dropdown badge every entry with it.
 */
export type PromptRegister = "professional" | "casual" | "technical" | "minimal" | "general"
/**
 * The outcome of testing one template against the last transcript. `after`
 * is None when the engine failed or skipped (the raw transcript would be
 * kept on the dictation path); `outcome` is the same token the run record
 * and history carry (`applied` | `skipped:<reason>` | `failed:<class>`,
 * or `skipped` for pre-run config states that never mint a run).
 */
export type PromptTestOutcome = { before: string; after: string | null; outcome: string; latency_ms: number }
export type RecordingRetentionPeriod = "never" | "preserve_limit" | "days_3" | "weeks_2" | "months_3"
export type SecretMap = Partial<{ [key in string]: string }>
export type SecureInputStatus = { 
/**
 * Secure input is currently enabled (live check)
 */
enabled: boolean; 
/**
 * Enabled continuously long enough to be considered stuck (not just a
 * password field gaining momentary focus)
 */
sustained: boolean; culprit_pid: number | null; culprit_name: string | null; 
/**
 * Carbon fallback registrations are currently active
 */
fallback_active: boolean; 
/**
 * Binding ids shadow-registered with identical semantics
 */
covered_bindings: string[]; 
/**
 * Side-specific binding ids widened to match either side while shadowed
 */
degraded_bindings: string[]; 
/**
 * Binding ids that cannot fire at all (e.g. fn+key, registration failure)
 */
uncovered_bindings: string[]; 
/**
 * The user tried to record a shortcut while secure input was active.
 * Treated as user impact even when every binding is covered, so the
 * warning banner appears and explains why recording refused.
 */
recorder_blocked: boolean }
/**
 * How the transcribe shortcut's key events drive a recording.
 */
export type ShortcutActivation = 
/**
 * Press to start, press again to stop.
 */
"toggle" | 
/**
 * Hold to record, release to stop.
 */
"push_to_talk" | 
/**
 * Hold to record and release to stop, or tap to keep recording until the
 * next press. Which one it was is decided by how long the key was held
 * (`hold_threshold_ms`).
 */
"hold_or_toggle"
export type ShortcutBinding = { id: string; name: string; description: string; default_binding: string; current_binding: string }
/**
 * Why a post-process pass fell back to the raw transcript. Carried on the
 * skip event so the frontend toast can name the cause; `memory_gate`
 * includes the formatted refusal numbers in the event detail.
 */
export type SkipReason = "memory_gate" | "download_missing" | "engine_failed" | "timeout" | "length_guard" | "too_long"
export type SoundTheme = "marimba" | "pop" | "custom"
/**
 * Phase of the streaming overlay card, emitted to drive its UI state.
 */
export type StreamPhase = 
/**
 * Receiving audio / live text (or waiting for the stream to begin). Rust
 * does not emit this today; the frontend starts in this phase and Rust only
 * emits transitions away from it.
 */
"listening" | 
/**
 * Finalizing or post-processing - show a spinner.
 */
"working"
/**
 * Emitted to switch the streaming overlay to a working spinner.
 */
export type StreamPhaseEvent = { phase: StreamPhase; 
/**
 * Present only when `phase` is `Working`.
 */
kind?: StreamWorkKind | null }
/**
 * Live transcription snapshot emitted to the overlay during a streaming run.
 * `committed` is the append-only, flicker-free prefix; `tentative` is the
 * volatile suffix the model may still rewrite. `deleted` carries the text a
 * buffer-side deletion just removed (the delete-word hotkey or a command-mode
 * DeleteWord / DeleteLine) so the overlay can show what went; absent from
 * the payload entirely when nothing was deleted.
 */
export type StreamTextEvent = { committed: string; tentative: string; 
/**
 * Present only when a buffer-side deletion just removed text; the
 * payload omits the key entirely otherwise (the StreamPhaseEvent
 * `kind` precedent).
 */
deleted?: string | null }
/**
 * Semantic kind of "working" phase, used to localize the spinner label.
 */
export type StreamWorkKind = "transcribing" | "polishing"
/**
 * The Test Connection verdict, assembled by the command from the model
 * list, the completion probe, or the on-device state. `completion_ok` is
 * None when no probe ran (local/Apple providers, or no model selected);
 * `latency_ms` is the round-trip of the model-list request.
 */
export type TestConnectionResult = { model_list_ok: boolean; completion_ok: boolean | null; latency_ms: number | null; failure_class: PostProcessFailureClass | null; detail: string }
/**
 * Structured error for the test command: the tag is the failure the UI
 * keys on (`no_history` when there is nothing to test against,
 * `prompt_not_found` for a dangling template id, `other` for a history
 * store read failure).
 */
export type TestPromptError = { kind: "no_history" } | { kind: "prompt_not_found"; id: string } | { kind: "other"; detail: string }
/**
 * UI appearance mode. `System` follows the OS `prefers-color-scheme`; `Light`
 * and `Dark` force one of the two palettes Handy already ships.
 */
export type Theme = "system" | "light" | "dark"
export type TranscribeAcceleratorSetting = "auto" | "cpu" | "gpu"
export type TypingTool = "auto" | "wtype" | "kwtype" | "dotool" | "ydotool" | "xdotool"
/**
 * What the startup update check may do without asking. `ask` is the release
 * default because a tray-dwelling dictation app downloading ~20 MB on its
 * own at launch is surprising behavior; `download` fetches in the background
 * and still prompts before restarting; `install` swaps the bundle silently
 * so the new version is simply active on the next launch (the restart
 * prompt remains a prompt - the app never relaunches itself unprompted).
 * Old stores without the key deserialize to `ask` via the derived default.
 */
export type UpdatePolicy = "ask" | "download" | "install"
export type VadBackend = "silero" | "earshot"
export type WindowsMicrophonePermissionStatus = { supported: boolean; overall_access: PermissionAccess; device_access: PermissionAccess; app_access: PermissionAccess; desktop_app_access: PermissionAccess }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
